### ISSUE TITLE
parse_child_nodes bug for str node_type

### ISSUE THREAD

**Issue by athensofamerica** [sangwonl/python-mpegdash#15]
In the parse_child_nodes defined in utils.py, when node type is (unicode, str), the call to "xmlnode.firstChild.nodeValue", appears to be wrong. When I change the call to parse_node_value(elem, node_type). It correctly passed the input mpd manifest file. This bug results in wrong parsed value to the Title element in the follow XML:

 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>inthewoods.mpd generated by GPAC</Title>
 </ProgramInformation>

def parse_child_nodes(xmlnode, tag_name, node_type):
    elements = _find_child_nodes_by_name(xmlnode, tag_name)
    if not elements:
        return None

    nodes = []
    for elem in elements:
        if node_type in (unicode, str):
            #node = xmlnode.firstChild.nodeValue           ### This seems to be wrong!!!
            node = parse_node_value(elem, node_type)  #This fixed the problem!
        else:
            node = node_type()
            node.parse(elem)
        nodes.append(node)

    return nodes

**Comment by sangwonl** [comment]
@athensofamerica thanks for the issue report. while I'm looking into this, but I can't reproduce the problem with the sample MPD contents in test case. It will be very helpful if you provide a sample MPD file reproducing the issue.

**Comment by isaiah1112** [comment]
Would this cause the following parsing issue I'm seeing?  Essentially I have an mpd with a muxed representation in an adapataton set but when I look into the sub-representation I see the following:

```{'profiles': None, 'width': None, 'height': None, 'sar': None, 'frame_rate': None, 'audio_sampling_rate': None, 'mime_type': None, 'segment_profiles': None, 'codecs': 'mp4a.40.5', 'maximum_sap_period': None, 'start_with_sap': None, 'max_playout_rate': None, 'coding_dependency': None, 'scan_type': None, 'frame_packings': None, 'audio_channel_configurations': None, 'content_protections': None, 'essential_properties': None, 'supplemental_properties': None, 'inband_event_streams': None, 'level': None, 'bandwidth': 117600, 'dependency_level': None, 'content_component': [<class 'str'>]}```

Note the `'content_component': [<class 'str'>]` didn't actually parse it out to the value of that xml, in this case it was: `<SubRepresentation bandwidth="117600" codecs="mp4a.40.5" contentComponent="102"></SubRepresentation>`

**Comment by sangwonl** [comment]
@isaiah1112 I brought a patch for the issue you mentioned. Could you try it and let me know if it works?

**Comment by isaiah1112** [comment]
> @isaiah1112 I brought a patch for the issue you mentioned. Could you try it and let me know if it works?

I'll check it out!

**Comment by sangwonl** [comment]
Closing this issue for now since it looks to work with the patch, but if it's still happening please file a new issue. Thanks.
