### ISSUE TITLE
About  viedo mpd

### ISSUE THREAD

**Issue by greenwheat1997** [sangwonl/python-mpegdash#39]
Can this code get the MPD file of the specified video link？

**Comment by davemevans** [comment]
If you mean can python-mpegdash retrieve a manifest from a specified URL and parse it the yes - see the example in https://github.com/sangwonl/python-mpegdash/blob/master/README.md#usage.

If you mean can python-mpegdash retrieve the manifest associated with some other type of URL eg https://www.youtube.com/watch?v=dQw4w9WgXcQ then no - you'd need to use some other library to get the manifest URL then pass it to python-mpegdash.

**Comment by greenwheat1997** [comment]
Thanks,I'll try to do it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2021年3月16日(星期二) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sangwonl/python-mpegdash] About  viedo mpd (#39)





 
If you mean can python-mpegdash retrieve a manifest from a specified URL and parse it the yes - see the example in https://github.com/sangwonl/python-mpegdash/blob/master/README.md#usage.
 
If you mean can python-mpegdash retrieve the manifest associated with some other type of URL eg https://www.youtube.com/watch?v=dQw4w9WgXcQ then no - you'd need to use some other library to get the manifest URL then pass it to python-mpegdash.

**Comment by sangwonl** [comment]
Believe the question was answered, so closing the issue. Thanks.
